spring :
  datasource:
    url: jdbc:mysql://localhost:3306/SkyStationManagement?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimeZoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

## Specify the DBMS
  jpa:
    database: MYSQL
    show-sql: false
## Hibernate DDL Auto ( Create , create-drop , update )
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080

flickr:
  apiKey: 4fb1af52a7377984c7d61c64a452754f
  apiSecret: 1f07d3a2506f1466