spring :
  datasource:
    url: jdbc:mysql://localhost:3307/trainingManagement?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimeZoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

## Specify the DBMS
  jpa:
    database: MYSQL
    show-sql: false
## Hibernate DDL Auto ( Create , create-drop , update )
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MYSQL5Dialect
server:
  port: 8080